export const designTokens = {
  color: {
    light: {
      canvas: '#f8fafc',
      surface: '#ffffff',
      surfaceMuted: '#eff6ff',
      border: '#cbd5e1',
      text: '#0f172a',
      textMuted: '#475569',
      primary: '#2563eb',
      primaryText: '#ffffff',
      secondary: '#1d4ed8',
      accent: '#0ea5e9',
      success: '#16a34a',
      info: '#0284c7',
      warning: '#d97706',
      error: '#dc2626',
      focus: '#1d4ed8',
    },
    dark: {
      canvas: '#020617',
      surface: '#0f172a',
      surfaceMuted: '#1e293b',
      border: '#334155',
      text: '#f8fafc',
      textMuted: '#cbd5e1',
      primary: '#60a5fa',
      primaryText: '#020617',
      secondary: '#93c5fd',
      accent: '#38bdf8',
      success: '#4ade80',
      info: '#38bdf8',
      warning: '#fbbf24',
      error: '#f87171',
      focus: '#93c5fd',
    },
  },
  typography: {
    familySans:
      'Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    familyMono: '"SFMono-Regular", "SF Mono", Consolas, "Liberation Mono", ui-monospace, monospace',
    size: {
      xs: '0.75rem',
      sm: '0.8125rem',
      base: '0.875rem',
      md: '0.9375rem',
      lg: '1.125rem',
      xl: '1.375rem',
      '2xl': '1.75rem',
    },
  },
  spacing: {
    px: '1px',
    0: '0',
    1: '0.25rem',
    2: '0.5rem',
    3: '0.75rem',
    4: '1rem',
    5: '1.25rem',
    6: '1.5rem',
    8: '2rem',
  },
  radius: {
    xs: '2px',
    sm: '4px',
    md: '6px',
    lg: '8px',
  },
  component: {
    controlHeightSm: '1.75rem',
    controlHeightMd: '2rem',
    iconButton: '2rem',
    rowHeight: '2.75rem',
    toolbarHeight: '2.5rem',
    sidebarWidth: '17rem',
    contextPanelWidth: '20rem',
  },
  focus: {
    ring: '0 0 0 2px var(--yife-focus)',
  },
  layer: {
    base: 0,
    nav: 20,
    overlay: 40,
    modal: 50,
    toast: 60,
  },
  nuxtUi: {
    colors: ['primary', 'secondary', 'success', 'info', 'warning', 'error', 'neutral'],
    defaultVariants: {
      color: 'neutral',
      size: 'sm',
    },
  },
} as const;

export type DesignTokens = typeof designTokens;
