export const designTokens = {
  color: {
    light: {
      canvas: '#f7f8f6',
      surface: '#ffffff',
      surfaceMuted: '#eef1ee',
      border: '#d9ded7',
      text: '#18201c',
      textMuted: '#5f6b63',
      primary: '#2f6f5e',
      primaryText: '#ffffff',
      secondary: '#4d5f91',
      accent: '#8b5e34',
      success: '#287a4b',
      info: '#2f6f8f',
      warning: '#a06715',
      error: '#b83f3f',
      focus: '#2563eb',
    },
    dark: {
      canvas: '#101312',
      surface: '#181d1b',
      surfaceMuted: '#202724',
      border: '#344039',
      text: '#edf2ee',
      textMuted: '#a8b3ac',
      primary: '#72b6a2',
      primaryText: '#0d1713',
      secondary: '#9ca9d8',
      accent: '#d0a06b',
      success: '#7cc995',
      info: '#82bdd3',
      warning: '#e0ad5f',
      error: '#e78181',
      focus: '#93c5fd',
    },
  },
  typography: {
    familySans:
      'Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    familyMono: '"SFMono-Regular", "SF Mono", Consolas, "Liberation Mono", ui-monospace, monospace',
    size: {
      xs: '0.75rem',
      sm: '0.8125rem',
      base: '0.875rem',
      md: '0.9375rem',
      lg: '1.125rem',
      xl: '1.375rem',
      '2xl': '1.75rem',
    },
  },
  spacing: {
    px: '1px',
    0: '0',
    1: '0.25rem',
    2: '0.5rem',
    3: '0.75rem',
    4: '1rem',
    5: '1.25rem',
    6: '1.5rem',
    8: '2rem',
  },
  radius: {
    xs: '2px',
    sm: '4px',
    md: '6px',
    lg: '8px',
  },
  component: {
    controlHeightSm: '1.75rem',
    controlHeightMd: '2rem',
    iconButton: '2rem',
    rowHeight: '2.75rem',
    toolbarHeight: '2.5rem',
    sidebarWidth: '17rem',
    contextPanelWidth: '20rem',
  },
  focus: {
    ring: '0 0 0 2px var(--yife-focus)',
  },
  layer: {
    base: 0,
    nav: 20,
    overlay: 40,
    modal: 50,
    toast: 60,
  },
  nuxtUi: {
    colors: ['primary', 'secondary', 'success', 'info', 'warning', 'error', 'neutral'],
    defaultVariants: {
      color: 'neutral',
      size: 'sm',
    },
  },
} as const;

export type DesignTokens = typeof designTokens;
